import type { EvidenceConfidence, ExerciseStage, LoadLevel, LoadTargetId, MuscleGroupId, RecommendationReason, RecommendationReasonTone, SecondaryGroupContext, WorkoutExercise, WorkoutRecommendation } from '../types/workout';

const levelValue:Record<LoadLevel,number>={low:1,medium:2,high:3};
const toLevel=(value:number):LoadLevel=>value>=8?'high':value>=4?'medium':'low';
const sets=(value:string)=>Number.parseInt(value,10)||3;
const effort=(rir:string)=>rir.startsWith('0')?1.15:rir.startsWith('1')?1:rir.startsWith('2')?.85:.7;
const exposure=(exercise:WorkoutExercise,target:LoadTargetId,index:number)=>(exercise.expectedSecondaryExposure[target]??0)*sets(exercise.sets)*effort(exercise.rir)*(index===0?1:.9)/3;
export function createReason(id:string,text:string,tone:RecommendationReasonTone,ruleId:string):RecommendationReason{return{id,text,tone,ruleId};}
export function accumulateFocusMetrics(exercises:WorkoutExercise[]){return exercises.flatMap(item=>item.focus.metrics).reduce<Record<string,number>>((sum,metric)=>({...sum,[metric.id]:(sum[metric.id]??0)+metric.value}),{});}
interface AccumulatedStimulusProfile{lengthenedScore:number;shortenedScore:number;stabilityDemandScore:number;systemicFatigueScore:number}
export function getAccumulatedStimulusProfile(exercises:WorkoutExercise[]):AccumulatedStimulusProfile{return exercises.reduce((sum,item)=>({lengthenedScore:sum.lengthenedScore+item.profile.lengthenedBias,shortenedScore:sum.shortenedScore+item.profile.contractionBias,stabilityDemandScore:sum.stabilityDemandScore+levelValue[item.practicalProperties.stabilityDemand],systemicFatigueScore:sum.systemicFatigueScore+levelValue[item.practicalProperties.systemicFatigue]}),{lengthenedScore:0,shortenedScore:0,stabilityDemandScore:0,systemicFatigueScore:0});}

export function getSecondaryGroupContext(primaryExercises:WorkoutExercise[],secondaryMuscleGroupId:MuscleGroupId):SecondaryGroupContext{const total=(target:LoadTargetId)=>primaryExercises.reduce((sum,exercise,index)=>sum+exposure(exercise,target,index),0);const exposureLevel=toLevel(total(secondaryMuscleGroupId));const maxProperty=(key:'lowerBackDemand'|'elbowDemand'|'shoulderDemand'|'systemicFatigue'):LoadLevel=>primaryExercises.reduce<LoadLevel>((max,item)=>levelValue[item.practicalProperties[key]]>levelValue[max]?item.practicalProperties[key]:max,'low');return{exposureLevel,jointLoad:{lowerBack:maxProperty('lowerBackDemand'),grip:toLevel(total('grip')),elbows:maxProperty('elbowDemand'),shoulders:maxProperty('shoulderDemand'),systemic:maxProperty('systemicFatigue')},notes:[exposureLevel==='high'?'Второстепенная группа уже заметно участвовала в основных упражнениях.':exposureLevel==='medium'?'Второстепенная группа получила умеренное косвенное участие.':'Косвенное участие второстепенной группы остаётся невысоким.']};}

type RuleState={score:number;reasons:RecommendationReason[];confidence:EvidenceConfidence;rule:string};
const add=(state:RuleState,candidate:WorkoutExercise,id:string,text:string,tone:RecommendationReasonTone,ruleId:string,score:number,confidence:EvidenceConfidence=state.confidence)=>{state.score+=score;state.reasons.push(createReason(`${candidate.id}-${id}`,text,tone,ruleId));state.rule=text;state.confidence=confidence;};

function applyChestRules(state:RuleState,candidate:WorkoutExercise,selected:WorkoutExercise[]){const previous=selected.at(-1);const focus=accumulateFocusMetrics(selected);const stimulus=getAccumulatedStimulusProfile(selected);if(previous?.profile.movementPattern==='horizontal_press'&&candidate.profile.movementPattern==='incline_press')add(state,candidate,'incline-after-horizontal','После горизонтального жима добавляет работу верхней части груди.','positive','chest-incline-after-horizontal',3,'moderate');if(previous?.practicalProperties.stabilityDemand==='high'&&candidate.practicalProperties.stabilityDemand==='low')add(state,candidate,'stable-after-free','Тренажёр снижает требования к стабилизации после тяжёлого свободного жима.','positive','stable-after-free-weight',2,'coaching_heuristic');if((focus.upper??0)>(focus.middle??0)+3&&candidate.stimulusTags.includes('upper_region_focus'))add(state,candidate,'upper-duplicate','Повторяет уже выраженный акцент на верх груди и снова нагружает переднюю дельту.','negative','chest-upper-focus-duplicate',-3,'limited');if(selected.length>=2&&candidate.profile.movementPattern==='chest_fly')add(state,candidate,'local-after-presses','После двух жимов добавляет объём грудным без третьего тяжёлого жимового движения.','positive','chest-local-after-two-presses',3,'coaching_heuristic');if(stimulus.lengthenedScore>=8&&candidate.stimulusTags.includes('shortened_emphasis'))add(state,candidate,'shortened-balance','После двух движений с высокой нагрузкой в растяжении даёт стабильное сведение в сокращённой части амплитуды.','positive','chest-stimulus-balance',2,'limited');}
function applyTricepsRules(state:RuleState,candidate:WorkoutExercise,context?:SecondaryGroupContext){if(context?.exposureLevel==='high'&&candidate.profile.movementPattern==='compound_triceps_press')add(state,candidate,'compound-after-chest','Жим снова нагружает грудь, плечи и трицепс после двух жимовых движений.','negative','triceps-compound-after-chest',-5,'coaching_heuristic');else if(context?.exposureLevel==='high')add(state,candidate,'local-after-chest','Трицепс уже участвовал в упражнениях на грудь, поэтому разгибание добавит локальную работу без ещё одного тяжёлого жима.','positive','triceps-local-after-chest',3,'coaching_heuristic');if(candidate.profile.movementPattern==='elbow_extension_overhead')add(state,candidate,'overhead-position','Положение плеча над головой увеличивает растяжение длинной головки, при этом весь трицепс продолжает участвовать.','positive','triceps-overhead-position',2,'moderate');}
function applyBackRules(state:RuleState,candidate:WorkoutExercise,selected:WorkoutExercise[]){const previous=selected.at(-1);if(previous?.profile.movementPattern==='vertical_pull'&&candidate.profile.movementPattern==='horizontal_pull')add(state,candidate,'horizontal-after-vertical','После вертикальной тяги добавляет горизонтальное направление и больше работы середине спины.','positive','back-complementary-direction',3,'coaching_heuristic');if(previous?.profile.movementPattern==='horizontal_pull'&&candidate.profile.movementPattern==='vertical_pull')add(state,candidate,'vertical-after-horizontal','После горизонтальной тяги добавляет вертикальное направление и больше работы широчайшим.','positive','back-complementary-direction',3,'coaching_heuristic');if(previous?.practicalProperties.lowerBackDemand==='high'&&candidate.stimulusTags.includes('supported'))add(state,candidate,'support-after-row','После тяги без опоры вариант с поддержкой груди снижает требования к уставшей пояснице.','positive','back-supported-after-lower-back',3,'moderate');if(selected.filter(item=>(item.expectedSecondaryExposure.biceps??0)>=2).length>=2&&candidate.profile.movementPattern==='lat_isolation')add(state,candidate,'pullover-after-pulls','Бицепс уже активно участвовал в тягах, а пуловер продолжает работу спины с меньшим сгибанием локтя.','positive','back-pullover-after-biceps-load',3,'coaching_heuristic');}
function applyBicepsRules(state:RuleState,candidate:WorkoutExercise,context?:SecondaryGroupContext){if(context?.exposureLevel==='high'&&candidate.stimulusTags.includes('supported'))add(state,candidate,'supported-after-pulls','После большого объёма тяг опора помогает выполнять сгибание без раскачивания корпуса.','positive','biceps-supported-after-pulls',3,'coaching_heuristic');if(candidate.stimulusTags.includes('neutral_grip'))add(state,candidate,'neutral-grip','Нейтральный хват добавляет больше работы плечевой и плечелучевой мышцам.','positive','biceps-neutral-grip',2,'moderate');}
function applyLegsRules(state:RuleState,candidate:WorkoutExercise,selected:WorkoutExercise[]){if(selected.some(item=>item.profile.movementPattern==='hip_hinge')&&candidate.profile.movementPattern==='leg_curl')add(state,candidate,'curl-after-hinge','После разгибания таза добавляет сгибание колена, которого не было в предыдущем упражнении.','positive','legs-curl-after-hinge',4,'moderate');if(selected.some(item=>item.practicalProperties.lowerBackDemand==='high')&&candidate.practicalProperties.lowerBackDemand==='low'&&candidate.practicalProperties.stabilityDemand==='low')add(state,candidate,'machine-after-heavy','После тяжёлого движения упражнение в тренажёре продолжает работу без дополнительной нагрузки на поясницу.','positive','legs-machine-after-fatigue',2,'coaching_heuristic');}
function applyShoulderRules(state:RuleState,candidate:WorkoutExercise[] extends never[]?never:WorkoutExercise,selected:WorkoutExercise[]){if(candidate.profile.movementPattern==='lateral_raise')add(state,candidate,'direct-side-delt','Добавляет прямую работу средней дельты, которая меньше нагружается в жимах на грудь.','positive','shoulders-side-delt-priority',2,'coaching_heuristic');if(getAccumulatedStimulusProfile(selected).systemicFatigueScore>=5&&candidate.stimulusTags.includes('supported'))add(state,candidate,'seated-after-fatigue','После тяжёлых ног вариант с опорой требует меньше общей стабилизации, чем свободный жим стоя.','positive','shoulders-supported-after-legs',2,'coaching_heuristic');}

export function getIntraGroupRecommendations({muscleGroupId,stage,selectedExercises,candidates,secondaryContext}:{muscleGroupId:MuscleGroupId;stage:ExerciseStage;selectedExercises:WorkoutExercise[];candidates:WorkoutExercise[];secondaryContext?:SecondaryGroupContext}):WorkoutRecommendation[]{return candidates.map(candidate=>{const state:RuleState={score:0,reasons:[],confidence:'coaching_heuristic',rule:'Сравнение с уже выбранными упражнениями.'};if(muscleGroupId==='chest')applyChestRules(state,candidate,selectedExercises);if(muscleGroupId==='triceps')applyTricepsRules(state,candidate,secondaryContext);if(muscleGroupId==='back')applyBackRules(state,candidate,selectedExercises);if(muscleGroupId==='biceps')applyBicepsRules(state,candidate,secondaryContext);if(muscleGroupId==='legs')applyLegsRules(state,candidate,selectedExercises);if(muscleGroupId==='shoulders')applyShoulderRules(state,candidate,selectedExercises);if(candidate.practicalProperties.systemicFatigue==='low'&&!state.reasons.length)add(state,candidate,'manageable-fatigue',`После предыдущей работы ${candidate.name.toLowerCase()} позволяет продолжить тренировку без ещё одного тяжёлого многосуставного движения.`,'neutral','manageable-systemic-fatigue',1,'coaching_heuristic');if(stage.optional)add(state,candidate,'optional-stage','Это необязательный объём: добавляй его только при достаточном времени и восстановлении.','neutral','optional-stage',0,'coaching_heuristic');const status=state.score>=3?'recommended':state.score<=-1?'not_ideal':'suitable';return{exerciseId:candidate.id,status,reasons:state.reasons.slice(0,2),score:state.score,confidence:state.confidence,rule:state.rule};});}
export function sortWorkoutRecommendations(items:WorkoutExercise[],recommendations:WorkoutRecommendation[]){const map=new Map(recommendations.map(r=>[r.exerciseId,r]));const order={recommended:0,suitable:1,not_ideal:2};return[...items].sort((a,b)=>{const ar=map.get(a.id),br=map.get(b.id);return ar&&br?order[ar.status]-order[br.status]||br.score-ar.score:0;});}
