import { useMemo, useRef, useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { ExerciseStep } from '../components/ExerciseStep';
import { ReferenceModal, type ReferenceType } from '../components/ReferenceModal';
import { UniversalExerciseModal } from '../components/UniversalExerciseModal';
import { WorkoutImpactPanel } from '../components/WorkoutImpactPanel';
import { WorkoutStepNavigator } from '../components/WorkoutStepNavigator';
import { WorkoutSummary } from '../components/WorkoutSummary';
import { workoutDays } from '../config/workoutDays';
import { exerciseStages } from '../data/exerciseStages';
import { workoutExercises } from '../data/workoutExercises';
import { getIntraGroupRecommendations, getSecondaryGroupContext, sortWorkoutRecommendations } from '../recommendations/workoutRecommendations';
import { getWorkoutSteps } from '../recommendations/workoutSteps';
import type { ExerciseStage, ExerciseStageId, MuscleGroupId, WorkoutDayId, WorkoutDaySelection, WorkoutExercise, WorkoutRecommendation } from '../types/workout';

export function WorkoutDayPage(){
  const{id}=useParams();const day=workoutDays[id as WorkoutDayId];
  const[selection,setSelection]=useState<WorkoutDaySelection>({});const[skippedStageIds,setSkippedStageIds]=useState<Set<ExerciseStageId>>(()=>new Set());const[activeStepIndex,setActiveStepIndex]=useState(0);const[modal,setModal]=useState<WorkoutExercise|null>(null);const[reference,setReference]=useState<ReferenceType|null>(null);const contentRef=useRef<HTMLDivElement>(null);
  if(!day)return <Navigate to="/" replace/>;
  const groups=[day.primaryMuscleGroup,day.secondaryMuscleGroup];const stages=exerciseStages.filter(stage=>groups.includes(stage.muscleGroupId));const steps=getWorkoutSteps(day,stages);const selectedByStage=new Map<string,WorkoutExercise>();for(const group of groups)for(const[stageId,exerciseId]of Object.entries(selection[group]??{})){const exercise=workoutExercises.find(item=>item.id===exerciseId);if(exercise)selectedByStage.set(stageId,exercise);}
  const selectedPrimary=steps.filter(step=>step.muscleGroupId===day.primaryMuscleGroup).map(step=>selectedByStage.get(step.stageId)).filter(Boolean)as WorkoutExercise[];const secondaryContext=getSecondaryGroupContext(selectedPrimary,day.secondaryMuscleGroup);
  const recommendationsByStep=useMemo(()=>{const map=new Map<string,WorkoutRecommendation[]>();for(const step of steps){const stage=stages.find(item=>item.id===step.stageId)!;const candidates=workoutExercises.filter(exercise=>exercise.stageId===step.stageId);const previous=steps.filter(item=>item.muscleGroupId===step.muscleGroupId&&stages.find(s=>s.id===item.stageId)!.order<stage.order).map(item=>selectedByStage.get(item.stageId)).filter(Boolean)as WorkoutExercise[];const hasContext=previous.length>0||(step.muscleGroupId===day.secondaryMuscleGroup&&selectedPrimary.length>0);map.set(step.stageId,hasContext?getIntraGroupRecommendations({muscleGroupId:step.muscleGroupId,stage,selectedExercises:previous,candidates,secondaryContext:step.muscleGroupId===day.secondaryMuscleGroup?secondaryContext:undefined}):[]);}return map;},[selection,id]);
  const recommendationByExercise=new Map<string,WorkoutRecommendation>();for(const list of recommendationsByStep.values())for(const recommendation of list)recommendationByExercise.set(recommendation.exerciseId,recommendation);
  const complete=steps.every(step=>selectedByStage.has(step.stageId)||(step.optional&&skippedStageIds.has(step.stageId)));const isSummary=activeStepIndex===steps.length;
  const goTo=(index:number)=>{setActiveStepIndex(index);requestAnimationFrame(()=>contentRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));};
  const selectExercise=(exercise:WorkoutExercise)=>{const hadSelection=selectedByStage.has(exercise.stageId);setSkippedStageIds(previous=>{const next=new Set(previous);next.delete(exercise.stageId);return next;});setSelection(previous=>({...previous,[exercise.muscleGroupId]:{...(previous[exercise.muscleGroupId]??{}),[exercise.stageId]:exercise.id}}));const currentIndex=steps.findIndex(step=>step.stageId===exercise.stageId);if(!hadSelection&&currentIndex>=0){const canFinish=steps.every(step=>step.stageId===exercise.stageId||selectedByStage.has(step.stageId)||(step.optional&&skippedStageIds.has(step.stageId)));const next=currentIndex+1<steps.length?currentIndex+1:canFinish?steps.length:currentIndex;setTimeout(()=>goTo(next),120);}};
  const skipStage=(stage:ExerciseStage)=>{if(!stage.optional)return;setSelection(previous=>{const groupSelection={...(previous[stage.muscleGroupId]??{})};delete groupSelection[stage.id];return{...previous,[stage.muscleGroupId]:groupSelection};});setSkippedStageIds(previous=>new Set(previous).add(stage.id));const currentIndex=steps.findIndex(step=>step.stageId===stage.id);if(currentIndex>=0){const canFinish=steps.every(step=>step.stageId===stage.id||selectedByStage.has(step.stageId)||(step.optional&&skippedStageIds.has(step.stageId)));const next=currentIndex+1<steps.length?currentIndex+1:canFinish?steps.length:currentIndex;setTimeout(()=>goTo(next),120);}};
  const activeStep=steps[activeStepIndex];const activeStage=activeStep?stages.find(stage=>stage.id===activeStep.stageId):undefined;const candidates=activeStep?sortWorkoutRecommendations(workoutExercises.filter(exercise=>exercise.stageId===activeStep.stageId),recommendationsByStep.get(activeStep.stageId)??[]):[];
  return <><nav className="topbar"><div className="topbar-inner"><Link className="brand" to="/"><div className="brand-mark">TH</div><span>Training Handbook</span></Link></div></nav><main className="shell chest-shell"><div className="breadcrumbs-row"><Link className="back-link" to="/">←</Link><nav className="breadcrumbs"><Link to="/">Главная</Link><span>/</span><span>{day.title}</span></nav></div><header className="page-head"><div><h1>{day.title}</h1><p>{day.description}</p></div></header><div className="reference-actions two"><button className="reference-button" onClick={()=>setReference('stages')}><strong>Этапы тренировки</strong><span>Порядок и диапазоны</span></button><button className="reference-button" onClick={()=>setReference('progression')}><strong>Прогрессия и рабочий вес</strong><span>Как подобрать и повышать вес</span></button></div><WorkoutStepNavigator steps={steps} stages={stages} activeIndex={activeStepIndex} selected={selectedByStage} skipped={skippedStageIds} recommendations={recommendationByExercise} onStep={goTo} onSummary={()=>goTo(steps.length)} complete={complete}/><WorkoutImpactPanel exercises={selectedPrimary} targetGroup={day.secondaryMuscleGroup}/><div className="step-content" ref={contentRef}>{isSummary?<WorkoutSummary groups={groups} stages={stages} selected={selectedByStage} recommendations={recommendationByExercise} onEdit={stageId=>goTo(steps.findIndex(step=>step.stageId===stageId))} onOpen={setModal}/>:activeStage&&<ExerciseStep stepNumber={activeStepIndex+1} total={steps.length} stage={activeStage} candidates={candidates} recommendations={new Map((recommendationsByStep.get(activeStage.id)??[]).map(item=>[item.exerciseId,item]))} selectedId={selection[activeStep.muscleGroupId]?.[activeStage.id]} skipped={skippedStageIds.has(activeStage.id)} onOpen={setModal} onSelect={selectExercise} onSkip={()=>skipStage(activeStage)}/>}</div></main><ReferenceModal type={reference} stages={stages} context={secondaryContext} onClose={()=>setReference(null)}/><UniversalExerciseModal exercise={modal} stage={modal?stages.find(stage=>stage.id===modal.stageId):undefined} recommendation={modal?recommendationByExercise.get(modal.id):undefined} selectedExercises={[...selectedByStage.values()]} selected={modal?selectedByStage.get(modal.stageId)?.id===modal.id:false} onSelect={()=>{if(modal)selectExercise(modal)}} onClose={()=>setModal(null)}/></>;
}
