import { useMemo, useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { UniversalExerciseCard } from '../components/UniversalExerciseCard';
import { UniversalExerciseModal } from '../components/UniversalExerciseModal';
import { ReferenceModal, type ReferenceType } from '../components/ReferenceModal';
import { WorkoutDayCurrentWorkout } from '../components/WorkoutDayCurrentWorkout';
import { muscleGroupLabels, workoutDays } from '../config/workoutDays';
import { exerciseStages } from '../data/exerciseStages';
import { workoutExercises } from '../data/workoutExercises';
import { getIntraGroupRecommendations, getSecondaryGroupContext, sortWorkoutRecommendations } from '../recommendations/workoutRecommendations';
import type { ExerciseStage, MuscleGroupId, WorkoutDayId, WorkoutDaySelection, WorkoutExercise, WorkoutRecommendation } from '../types/workout';

export function WorkoutDayPage(){const{id}=useParams();const day=workoutDays[id as WorkoutDayId];const[activeGroup,setActiveGroup]=useState<MuscleGroupId|undefined>(day?.primaryMuscleGroup);const[selection,setSelection]=useState<WorkoutDaySelection>({});const[query,setQuery]=useState('');const[focus,setFocus]=useState('');const[modal,setModal]=useState<WorkoutExercise|null>(null);const[reference,setReference]=useState<ReferenceType|null>(null);if(!day)return <Navigate to="/" replace/>;const groups=[day.primaryMuscleGroup,day.secondaryMuscleGroup];const stages=exerciseStages.filter(s=>groups.includes(s.muscleGroupId));const currentGroup=activeGroup??day.primaryMuscleGroup;const groupStages=stages.filter(s=>s.muscleGroupId===currentGroup).sort((a,b)=>a.order-b.order);const selectedExercises=(group:MuscleGroupId)=>Object.values(selection[group]??{}).map(id=>workoutExercises.find(e=>e.id===id)).filter(Boolean) as WorkoutExercise[];const secondaryContext=getSecondaryGroupContext(selectedExercises(day.primaryMuscleGroup),day.secondaryMuscleGroup);
 const stageView=useMemo(()=>groupStages.map(stage=>{const candidates=workoutExercises.filter(e=>e.stageId===stage.id).filter(e=>(!query||e.name.toLowerCase().includes(query.toLowerCase()))&&(!focus||e.focus.label===focus));const previous=groupStages.filter(s=>s.order<stage.order).map(s=>workoutExercises.find(e=>e.id===selection[currentGroup]?.[s.id])).filter(Boolean) as WorkoutExercise[];const hasPrimaryContext=selectedExercises(day.primaryMuscleGroup).length>0;const recs=previous.length||(currentGroup===day.secondaryMuscleGroup&&hasPrimaryContext)?getIntraGroupRecommendations({muscleGroupId:currentGroup,stage,selectedExercises:previous,candidates,secondaryContext:currentGroup===day.secondaryMuscleGroup?secondaryContext:undefined}):[];return{stage,candidates:sortWorkoutRecommendations(candidates,recs),recs};}),[currentGroup,focus,groupStages,query,secondaryContext,selection,day.primaryMuscleGroup,day.secondaryMuscleGroup]);
 const select=(exercise:WorkoutExercise)=>{const stage=exerciseStages.find(s=>s.id===exercise.stageId)!;setSelection(prev=>{const groupSelection={...(prev[exercise.muscleGroupId]??{})};for(const later of exerciseStages.filter(s=>s.muscleGroupId===exercise.muscleGroupId&&s.order>=stage.order))delete groupSelection[later.id];groupSelection[stage.id]=exercise.id;const next={...prev,[exercise.muscleGroupId]:groupSelection};if(exercise.muscleGroupId===day.primaryMuscleGroup)delete next[day.secondaryMuscleGroup];return next;});};
 const recommendationMap=(items:WorkoutRecommendation[])=>new Map(items.map(r=>[r.exerciseId,r]));
 return <><nav className="topbar"><div className="topbar-inner"><Link className="brand" to="/"><div className="brand-mark">TH</div><span>Training Handbook</span></Link></div></nav><main className="shell chest-shell"><div className="breadcrumbs-row"><Link className="back-link" to="/">←</Link><nav className="breadcrumbs"><Link to="/">Главная</Link><span>/</span><span>{day.title}</span></nav></div><header className="page-head"><div><h1>{day.title}</h1><p>{day.description}</p></div></header><div className="reference-actions"><button className="reference-button" onClick={()=>setReference('stages')}><strong>Этапы</strong><span>Порядок и диапазоны</span></button><button className="reference-button" onClick={()=>setReference('progression')}><strong>Прогрессия</strong><span>Рабочий вес</span></button><button className="reference-button" onClick={()=>setReference('secondary')}><strong>Влияние групп</strong><span>Косвенная нагрузка</span></button></div><div className="muscle-switcher">{groups.map(group=><button className={currentGroup===group?'active':''} onClick={()=>setActiveGroup(group)} key={group}><span>{group===day.primaryMuscleGroup?'Основная группа':'Второстепенная группа'}</span><strong>{muscleGroupLabels[group]}</strong></button>)}</div>{currentGroup===day.secondaryMuscleGroup&&<div className="secondary-context panel"><strong>Влияние основной группы</strong><p>{secondaryContext.notes.join(' ')}</p></div>}<div className="exercise-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск упражнения…"/><select value={focus} onChange={e=>setFocus(e.target.value)}><option value="">Любой акцент</option>{[...new Set(workoutExercises.filter(e=>e.muscleGroupId===currentGroup).map(e=>e.focus.label))].map(x=><option key={x}>{x}</option>)}</select></div><div className="exercise-catalog-layout"><div className="exercise-sections">{stageView.map(({stage,candidates,recs})=><GenericStage key={stage.id} stage={stage} candidates={candidates} recommendations={recommendationMap(recs)} selectedId={selection[currentGroup]?.[stage.id]} onOpen={setModal} onSelect={select}/>)}</div><WorkoutDayCurrentWorkout groups={groups} stages={stages} exercises={workoutExercises} selection={selection} onClearGroup={group=>setSelection(prev=>({...prev,[group]:{}}))} onClearAll={()=>setSelection({})}/></div></main><ReferenceModal type={reference} stages={groupStages} context={secondaryContext} onClose={()=>setReference(null)}/><UniversalExerciseModal exercise={modal} stage={modal?exerciseStages.find(s=>s.id===modal.stageId):undefined} selected={Boolean(modal&&selection[modal.muscleGroupId]?.[modal.stageId]===modal.id)} onClose={()=>setModal(null)} onSelect={select}/></>}

function GenericStage({stage,candidates,recommendations,selectedId,onOpen,onSelect}:{stage:ExerciseStage;candidates:WorkoutExercise[];recommendations:Map<string,WorkoutRecommendation>;selectedId?:string;onOpen:(e:WorkoutExercise)=>void;onSelect:(e:WorkoutExercise)=>void}){return <section className="exercise-stage-section"><header className="exercise-stage-head"><div><span className="stage-tag s2">{stage.order}. {stage.shortTitle}{stage.optional?' · опционально':''}</span><h2>{stage.title}</h2><p>{stage.description}</p></div><strong>{stage.reps}</strong></header>{candidates.length?<div className="exercise-card-grid">{candidates.map(e=><UniversalExerciseCard key={e.id} exercise={e} recommendation={recommendations.get(e.id)} selected={selectedId===e.id} onOpen={()=>onOpen(e)} onSelect={()=>onSelect(e)}/>)}</div>:<div className="empty-stage panel">По текущему фильтру упражнений нет.</div>}</section>}
